const CITIES_DATA = [
  {
    id: "riyadh",
    name: "المدينة الصناعية الأولى - الرياض",
    nameEn: "First Industrial City - Riyadh",
    region: "منطقة الرياض",
    coordinates: { lat: 24.7136, lng: 46.6753 },
    mapX: 52,
    mapY: 48,
    established: 1975,
    area: 8100000,
    areaUnit: "م²",
    factories: 850,
    workers: 120000,
    image: "riyadh_first_industrial_city.png",
    heroImage: "riyadh_first_industrial_city.png",
    description: "تُعدّ المدينة الصناعية الأولى في الرياض من أبرز المدن الصناعية في المملكة العربية السعودية، وتمثل نموذجاً متكاملاً للتطوير الصناعي المستدام. تضم المدينة مئات المنشآت الصناعية المتنوعة التي تغطي قطاعات متعددة.",
    industries: ["البتروكيماويات", "الصناعات الغذائية", "مواد البناء", "الصناعات الدوائية", "الصناعات الهندسية", "التعبئة والتغليف"],
    services: ["بنية تحتية متكاملة", "شبكة طرق داخلية", "خدمات المياه والكهرباء", "مستودعات لوجستية", "مراكز خدمات الأعمال", "مناطق سكنية للعمال"],
    vision2030Role: "تسهم المدينة في تحقيق مستهدفات رؤية 2030 من خلال تنويع مصادر الدخل الوطني، وتوطين الصناعات الاستراتيجية، وخلق فرص عمل للكوادر السعودية.",
    investmentHighlights: ["إعفاءات جمركية", "أراضٍ صناعية بأسعار تنافسية", "دعم حكومي للمصانع الجديدة", "قرب من مراكز التوزيع"],
    gdpContribution: 18.5,
    exportValue: 12.3,
    saudiEmployment: 35,
    color: "#D4AF37",
    stats: {
      annualProduction: "45 مليار ريال",
      exportPercentage: "62%",
      localContent: "48%"
    }
  },
  {
    id: "jeddah",
    name: "المدينة الصناعية - جدة",
    nameEn: "Industrial City - Jeddah",
    region: "منطقة مكة المكرمة",
    coordinates: { lat: 21.4858, lng: 39.1925 },
    mapX: 35,
    mapY: 55,
    established: 1977,
    area: 12500000,
    areaUnit: "م²",
    factories: 1200,
    workers: 180000,
    image: "jeddah_industrial_city.png",
    heroImage: "jeddah_industrial_city.png",
    description: "تتميز المدينة الصناعية في جدة بموقعها الاستراتيجي على ساحل البحر الأحمر، مما يمنحها ميزة تنافسية استثنائية في مجال التجارة الدولية والتصدير. تضم المدينة أكبر تجمع للصناعات التحويلية في المنطقة الغربية.",
    industries: ["الصناعات البحرية", "الصناعات الغذائية والمشروبات", "الصناعات الكيماوية", "الصناعات النسيجية", "الصناعات الإلكترونية", "اللوجستيات والتوزيع"],
    services: ["ميناء جدة الإسلامي", "مستودعات جمركية", "مناطق حرة", "خدمات الشحن والتخليص", "مراكز التدريب المهني", "خدمات المرافق المتكاملة"],
    vision2030Role: "تدعم المدينة مستهدفات رؤية 2030 في تطوير قطاع اللوجستيات وجعل المملكة مركزاً لوجستياً عالمياً، فضلاً عن تعزيز الصادرات غير النفطية.",
    investmentHighlights: ["قرب من ميناء جدة الإسلامي", "مناطق حرة للتصدير", "بنية تحتية عالمية المستوى", "سهولة الوصول للأسواق الدولية"],
    gdpContribution: 22.1,
    exportValue: 18.7,
    saudiEmployment: 38,
    color: "#C9A961",
    stats: {
      annualProduction: "68 مليار ريال",
      exportPercentage: "75%",
      localContent: "52%"
    }
  },
  {
    id: "jubail",
    name: "مدينة الجبيل الصناعية",
    nameEn: "Jubail Industrial City",
    region: "المنطقة الشرقية",
    coordinates: { lat: 27.0174, lng: 49.6580 },
    mapX: 68,
    mapY: 42,
    established: 1975,
    area: 1000000000,
    areaUnit: "م²",
    factories: 300,
    workers: 100000,
    image: "jubail_industrial_city.png",
    heroImage: "jubail_industrial_city.png",
    description: "تُعدّ مدينة الجبيل الصناعية واحدة من أكبر مشاريع التطوير الصناعي في العالم، وتمثل قلب الصناعة البتروكيماوية في المملكة العربية السعودية. تضم المدينة أضخم مجمع صناعي بتروكيماوي على مستوى العالم.",
    industries: ["البتروكيماويات الأساسية", "الصناعات البلاستيكية", "صناعة الحديد والصلب", "الصناعات الكيماوية المتخصصة", "صناعة الألمنيوم", "الصناعات المعدنية"],
    services: ["ميناء الجبيل التجاري", "ميناء الملك فهد الصناعي", "شبكة أنابيب متكاملة", "محطات توليد الطاقة", "مرافق تحلية المياه", "مدينة سكنية متكاملة"],
    vision2030Role: "تُشكّل الجبيل الصناعية ركيزة أساسية في تحقيق رؤية 2030 من خلال قيادة التحول الصناعي وتطوير سلاسل القيمة المضافة للبتروكيماويات وتصدير المنتجات عالية القيمة.",
    investmentHighlights: ["أكبر مجمع بتروكيماوي عالمياً", "بنية تحتية صناعية فريدة", "شراكات استراتيجية دولية", "دعم متكامل من هيئة المدن الصناعية"],
    gdpContribution: 35.2,
    exportValue: 45.8,
    saudiEmployment: 42,
    color: "#2C3E50",
    stats: {
      annualProduction: "180 مليار ريال",
      exportPercentage: "88%",
      localContent: "65%"
    }
  },
  {
    id: "yanbu",
    name: "مدينة ينبع الصناعية",
    nameEn: "Yanbu Industrial City",
    region: "منطقة المدينة المنورة",
    coordinates: { lat: 24.0895, lng: 38.0618 },
    mapX: 30,
    mapY: 45,
    established: 1975,
    area: 185000000,
    areaUnit: "م²",
    factories: 180,
    workers: 55000,
    image: "yanbu_industrial_city.png",
    heroImage: "yanbu_industrial_city.png",
    description: "تقع مدينة ينبع الصناعية على ساحل البحر الأحمر وتمثل الشريك الغربي لمدينة الجبيل الصناعية في المنطقة الشرقية. تتخصص المدينة في صناعات التكرير والبتروكيماويات وتصدير المنتجات النفطية.",
    industries: ["تكرير النفط", "البتروكيماويات", "الصناعات الكيماوية", "صناعة الأسمدة", "الصناعات البحرية", "صناعة مواد البناء"],
    services: ["ميناء ينبع التجاري", "ميناء ينبع الصناعي", "خطوط أنابيب النفط", "محطات الطاقة", "خدمات الموانئ المتكاملة", "مرافق التخزين"],
    vision2030Role: "تسهم ينبع الصناعية في تحقيق رؤية 2030 من خلال تطوير صناعات التكرير وتعزيز القيمة المضافة للنفط الخام، وتقوية الصادرات البتروكيماوية.",
    investmentHighlights: ["موقع استراتيجي على البحر الأحمر", "ربط مباشر بخطوط الأنابيب", "تسهيلات جمركية خاصة", "دعم لوجستي متكامل"],
    gdpContribution: 15.8,
    exportValue: 28.4,
    saudiEmployment: 39,
    color: "#34495E",
    stats: {
      annualProduction: "95 مليار ريال",
      exportPercentage: "82%",
      localContent: "58%"
    }
  },
  {
    id: "dammam",
    name: "المدينة الصناعية الثانية - الدمام",
    nameEn: "Second Industrial City - Dammam",
    region: "المنطقة الشرقية",
    coordinates: { lat: 26.4207, lng: 50.0888 },
    mapX: 70,
    mapY: 44,
    established: 1980,
    area: 9500000,
    areaUnit: "م²",
    factories: 650,
    workers: 85000,
    image: "dammam_second_industrial_city.png",
    heroImage: "dammam_second_industrial_city.png",
    description: "تُعدّ المدينة الصناعية الثانية في الدمام مركزاً صناعياً حيوياً في المنطقة الشرقية، وتستفيد من قربها من حقول النفط والموانئ البحرية. تضم المدينة تنوعاً صناعياً واسعاً يشمل قطاعات متعددة.",
    industries: ["الصناعات البتروكيماوية", "الصناعات الهندسية", "صناعة مواد البناء", "الصناعات الغذائية", "الصناعات الكيماوية", "الصناعات الخفيفة"],
    services: ["قرب من ميناء الملك عبدالعزيز", "شبكة طرق متكاملة", "خدمات الطاقة والمياه", "مستودعات لوجستية", "خدمات الدعم الصناعي", "مراكز الأعمال"],
    vision2030Role: "تدعم المدينة مستهدفات رؤية 2030 في تطوير القطاع الصناعي وتوطين الصناعات الاستراتيجية وخلق فرص عمل نوعية للكوادر الوطنية.",
    investmentHighlights: ["قرب من الموانئ والمطارات", "بيئة استثمارية محفزة", "دعم حكومي متكامل", "بنية تحتية متطورة"],
    gdpContribution: 12.4,
    exportValue: 15.6,
    saudiEmployment: 36,
    color: "#D4AF37",
    stats: {
      annualProduction: "52 مليار ريال",
      exportPercentage: "58%",
      localContent: "44%"
    }
  },
  {
    id: "sudair",
    name: "المدينة الصناعية - سدير",
    nameEn: "Sudair Industrial City",
    region: "منطقة الرياض",
    coordinates: { lat: 25.6500, lng: 45.5500 },
    mapX: 55,
    mapY: 43,
    established: 2010,
    area: 120000000,
    areaUnit: "م²",
    factories: 120,
    workers: 25000,
    image: "sudair_industrial_city.png",
    heroImage: "sudair_industrial_city.png",
    description: "تمثل المدينة الصناعية في سدير نموذجاً للتطوير الصناعي الحديث في المملكة العربية السعودية، وتتميز بتصميمها المتكامل الذي يجمع بين الاستدامة والكفاءة الصناعية.",
    industries: ["الصناعات الغذائية", "الصناعات الدوائية", "صناعة مواد البناء", "الصناعات الخفيفة", "الصناعات التحويلية", "التعبئة والتغليف"],
    services: ["بنية تحتية حديثة", "خدمات الطاقة المتجددة", "مراكز الابتكار الصناعي", "خدمات اللوجستيات", "مرافق التدريب", "خدمات الدعم الاستثماري"],
    vision2030Role: "تسهم في تحقيق رؤية 2030 من خلال التركيز على الصناعات المعرفية والتقنية، وتوطين الصناعات الغذائية والدوائية لتعزيز الأمن الغذائي والصحي.",
    investmentHighlights: ["موقع مركزي متميز", "تسهيلات استثمارية خاصة", "بيئة صناعية متكاملة", "دعم للشركات الناشئة"],
    gdpContribution: 5.2,
    exportValue: 4.8,
    saudiEmployment: 45,
    color: "#C9A961",
    stats: {
      annualProduction: "18 مليار ريال",
      exportPercentage: "35%",
      localContent: "55%"
    }
  },
  {
    id: "hail",
    name: "المدينة الصناعية - حائل",
    nameEn: "Hail Industrial City",
    region: "منطقة حائل",
    coordinates: { lat: 27.5219, lng: 41.6905 },
    mapX: 45,
    mapY: 35,
    established: 2005,
    area: 35000000,
    areaUnit: "م²",
    factories: 85,
    workers: 15000,
    image: "hail_industrial_city.png",
    heroImage: "hail_industrial_city.png",
    description: "تُعدّ المدينة الصناعية في حائل بوابة التطوير الصناعي في شمال المملكة العربية السعودية، وتتميز بتركيزها على الصناعات الزراعية والغذائية التي تستفيد من الإنتاج الزراعي الغني في المنطقة.",
    industries: ["الصناعات الزراعية والغذائية", "صناعة الأعلاف", "الصناعات الخفيفة", "صناعة مواد البناء", "الصناعات الحرفية", "التعبئة والتغليف الزراعي"],
    services: ["بنية تحتية أساسية", "خدمات الطاقة والمياه", "مستودعات تبريد", "خدمات النقل والتوزيع", "مراكز الدعم الزراعي", "خدمات التسويق"],
    vision2030Role: "تدعم رؤية 2030 في تحقيق الأمن الغذائي وتطوير القطاع الزراعي وتوفير فرص عمل في المناطق الشمالية وتقليل التفاوت الإقليمي.",
    investmentHighlights: ["وفرة المواد الخام الزراعية", "دعم حكومي للمشاريع الزراعية", "تكاليف تشغيل منخفضة", "سوق محلي واعد"],
    gdpContribution: 2.8,
    exportValue: 1.9,
    saudiEmployment: 48,
    color: "#2C3E50",
    stats: {
      annualProduction: "8 مليار ريال",
      exportPercentage: "22%",
      localContent: "62%"
    }
  },
  {
    id: "jizan",
    name: "المدينة الصناعية - جازان",
    nameEn: "Jizan Industrial City",
    region: "منطقة جازان",
    coordinates: { lat: 16.8892, lng: 42.5611 },
    mapX: 32,
    mapY: 72,
    established: 2008,
    area: 100000000,
    areaUnit: "م²",
    factories: 95,
    workers: 20000,
    image: "jazan_industrial_city.png",
    heroImage: "jazan_industrial_city.png",
    description: "تمثل المدينة الصناعية في جازان نقطة تحول استراتيجية في تطوير جنوب المملكة العربية السعودية، وتضم مجمع جازان الاقتصادي الذي يُعدّ من أضخم المشاريع الصناعية في المنطقة.",
    industries: ["تكرير النفط", "البتروكيماويات", "صناعة الصلب", "الصناعات الغذائية", "صناعة الأسمدة", "الصناعات الكيماوية"],
    services: ["ميناء جازان التجاري", "مجمع جازان الاقتصادي", "محطة توليد الطاقة", "خدمات الموانئ المتكاملة", "بنية تحتية حديثة", "مرافق التخزين والشحن"],
    vision2030Role: "تُسهم في تحقيق رؤية 2030 من خلال تطوير المنطقة الجنوبية وتوفير فرص العمل وتنويع الاقتصاد الإقليمي وتعزيز التكامل الاقتصادي مع دول القرن الأفريقي.",
    investmentHighlights: ["موقع استراتيجي قرب إفريقيا", "مجمع اقتصادي متكامل", "دعم حكومي استثنائي", "فرص في الصناعات الثقيلة"],
    gdpContribution: 4.5,
    exportValue: 6.2,
    saudiEmployment: 40,
    color: "#34495E",
    stats: {
      annualProduction: "22 مليار ريال",
      exportPercentage: "48%",
      localContent: "42%"
    }
  },
  {
    id: "taif",
    name: "المدينة الصناعية - الطائف",
    nameEn: "Taif Industrial City",
    region: "منطقة مكة المكرمة",
    coordinates: { lat: 21.2854, lng: 40.4150 },
    mapX: 37,
    mapY: 58,
    established: 1995,
    area: 15000000,
    areaUnit: "م²",
    factories: 110,
    workers: 18000,
    image: "taif_industrial_city.png",
    heroImage: "taif_industrial_city.png",
    description: "تتميز المدينة الصناعية في الطائف بموقعها الجبلي الفريد وتركيزها على الصناعات الخفيفة والغذائية، وتستفيد من شهرة الطائف بإنتاج الورد والمنتجات الزراعية المميزة.",
    industries: ["صناعة العطور والزيوت العطرية", "الصناعات الغذائية", "الصناعات الحرفية", "الصناعات الخفيفة", "التعبئة والتغليف", "الصناعات الدوائية"],
    services: ["بنية تحتية متكاملة", "خدمات الطاقة والمياه", "مراكز التدريب المهني", "خدمات الدعم الصناعي", "مرافق التخزين", "خدمات الأعمال"],
    vision2030Role: "تدعم رؤية 2030 في تطوير الصناعات الإبداعية والحرفية وتعزيز السياحة الصناعية وتوطين صناعة العطور والمنتجات الطبيعية.",
    investmentHighlights: ["تميز في صناعة العطور", "مناخ معتدل مناسب للصناعة", "قرب من مكة المكرمة", "سوق سياحي واعد"],
    gdpContribution: 3.2,
    exportValue: 2.8,
    saudiEmployment: 52,
    color: "#D4AF37",
    stats: {
      annualProduction: "12 مليار ريال",
      exportPercentage: "30%",
      localContent: "58%"
    }
  },
  {
    id: "madinah",
    name: "المدينة الصناعية - المدينة المنورة",
    nameEn: "Madinah Industrial City",
    region: "منطقة المدينة المنورة",
    coordinates: { lat: 24.5247, lng: 39.5692 },
    mapX: 38,
    mapY: 47,
    established: 1985,
    area: 10000000,
    areaUnit: "م²",
    factories: 200,
    workers: 30000,
    image: "madinah_industrial_city.png",
    heroImage: "madinah_industrial_city.png",
    description: "تُعدّ المدينة الصناعية في المدينة المنورة مركزاً صناعياً حيوياً يستفيد من موقعه القريب من الأماكن المقدسة وحركة الحجاج والمعتمرين. تتميز بتنوعها الصناعي وتركيزها على الصناعات الغذائية والاستهلاكية.",
    industries: ["الصناعات الغذائية", "صناعة التمور ومشتقاتها", "الصناعات الاستهلاكية", "الصناعات الخفيفة", "التعبئة والتغليف", "الصناعات الحرفية"],
    services: ["بنية تحتية متكاملة", "قرب من مطار الأمير محمد بن عبدالعزيز", "خدمات الطاقة والمياه", "مراكز التوزيع", "خدمات الدعم الصناعي", "مرافق اللوجستيات"],
    vision2030Role: "تسهم في رؤية 2030 من خلال تطوير الصناعات المرتبطة بالسياحة الدينية وتوطين صناعة التمور وتعزيز الاقتصاد المحلي.",
    investmentHighlights: ["سوق ضخم من الحجاج والمعتمرين", "تميز في صناعة التمور", "قرب من المطار الدولي", "دعم حكومي للمشاريع الصغيرة"],
    gdpContribution: 4.8,
    exportValue: 3.5,
    saudiEmployment: 50,
    color: "#C9A961",
    stats: {
      annualProduction: "16 مليار ريال",
      exportPercentage: "28%",
      localContent: "60%"
    }
  }
,
  {
    id: "alkharj",
    name: "المدينة الصناعية - الخرج",
    nameEn: "Industrial City - Al-Kharj",
    region: "منطقة الرياض",
    coordinates: { lat: 24.1500, lng: 47.3000 },
    mapX: 54,
    mapY: 52,
    established: 2009,
    area: 99000000,
    areaUnit: "م²",
    factories: 150,
    workers: 35000,
    image: "alkharj_industrial_city.png",
    heroImage: "alkharj_industrial_city.png",
    description: "تعتبر المدينة الصناعية بالخرج من المدن الواعدة التي تخدم منطقة الرياض، وتتميز بتنوع الصناعات فيها وقربها من العاصمة.",
    industries: ["الصناعات الغذائية", "الصناعات البلاستيكية", "صناعة مواد البناء", "الصناعات الكيماوية"],
    services: ["بنية تحتية متكاملة", "خدمات لوجستية", "محطات طاقة"],
    vision2030Role: "دعم التوسع الصناعي في منطقة الرياض وتوفير بدائل استثمارية متنوعة.",
    investmentHighlights: ["مساحات شاسعة", "قرب من العاصمة", "تسهيلات ائتمانية"],
    gdpContribution: 6.5,
    exportValue: 4.2,
    saudiEmployment: 38,
    color: "#D4AF37",
    stats: { annualProduction: "15 مليار ريال", exportPercentage: "30%", localContent: "50%" }
  },
  {
    id: "tabuk",
    name: "المدينة الصناعية - تبوك",
    nameEn: "Industrial City - Tabuk",
    region: "منطقة تبوك",
    coordinates: { lat: 28.3998, lng: 36.5715 },
    mapX: 20,
    mapY: 25,
    established: 2012,
    area: 4000000,
    areaUnit: "م²",
    factories: 45,
    workers: 8000,
    image: "tabuk_industrial_city.png",
    heroImage: "tabuk_industrial_city.png",
    description: "تخدم المدينة الصناعية في تبوك المنطقة الشمالية الغربية، وتكتسب أهمية متزايدة لقربها من مشروع نيوم.",
    industries: ["مواد البناء", "الصناعات الغذائية", "الصناعات الخفيفة"],
    services: ["خدمات أساسية", "طرق مجهزة", "دعم فني"],
    vision2030Role: "توفير الدعم الصناعي للمشاريع الكبرى في شمال غرب المملكة.",
    investmentHighlights: ["موقع استراتيجي قرب نيوم", "فرص في قطاع الإنشاءات"],
    gdpContribution: 2.1,
    exportValue: 1.2,
    saudiEmployment: 45,
    color: "#2C3E50",
    stats: { annualProduction: "4 مليار ريال", exportPercentage: "15%", localContent: "60%" }
  },
  {
    id: "arar",
    name: "المدينة الصناعية - عرعر",
    nameEn: "Industrial City - Arar",
    region: "منطقة الحدود الشمالية",
    coordinates: { lat: 30.9753, lng: 41.0381 },
    mapX: 42,
    mapY: 15,
    established: 2015,
    area: 2000000,
    areaUnit: "م²",
    factories: 25,
    workers: 3000,
    image: "arar_industrial_city.png",
    heroImage: "arar_industrial_city.png",
    description: "مدينة صناعية ناشئة تهدف لتطوير النشاط الصناعي في منطقة الحدود الشمالية.",
    industries: ["صناعات تعدينية", "صناعات خفيفة"],
    services: ["مرافق أساسية", "تسهيلات للمستثمرين"],
    vision2030Role: "تنمية المناطق الحدودية وخلق فرص عمل محلية.",
    investmentHighlights: ["حوافز استثمارية مجزية", "وفرة في الموارد التعدينية"],
    gdpContribution: 1.2,
    exportValue: 0.8,
    saudiEmployment: 55,
    color: "#C9A961",
    stats: { annualProduction: "2 مليار ريال", exportPercentage: "10%", localContent: "70%" }
  },
  {
    id: "najran",
    name: "المدينة الصناعية - نجران",
    nameEn: "Industrial City - Najran",
    region: "منطقة نجران",
    coordinates: { lat: 17.4933, lng: 44.1277 },
    mapX: 45,
    mapY: 80,
    established: 2010,
    area: 6500000,
    areaUnit: "م²",
    factories: 40,
    workers: 6000,
    image: "najran_industrial_city.png",
    heroImage: "najran_industrial_city.png",
    description: "تتميز المدينة الصناعية في نجران بتركيزها على الصناعات التي تستفيد من الموارد الطبيعية في المنطقة.",
    industries: ["صناعة الرخام والجرانيت", "مواد البناء", "الصناعات الغذائية"],
    services: ["بنية تحتية مطورة", "مراكز خدمات"],
    vision2030Role: "تعزيز الاستفادة من الثروات المعدنية في الجنوب وتطوير الصناعات التحويلية.",
    investmentHighlights: ["ثروات طبيعية هائلة", "موقع متميز للتصدير لدول الجوار"],
    gdpContribution: 1.8,
    exportValue: 1.5,
    saudiEmployment: 42,
    color: "#34495E",
    stats: { annualProduction: "3.5 مليار ريال", exportPercentage: "20%", localContent: "65%" }
  }
];


const ECONOMIC_STATS = {
  totalCities: 36,
  totalArea: "2.4 مليار م²",
  totalFactories: 9500,
  totalWorkers: 850000,
  gdpContribution: 12.5,
  annualExports: "285 مليار ريال",
  foreignInvestment: "145 مليار ريال",
  saudiEmploymentRate: 42,
  yearlyGrowth: 8.3,
  vision2030Target: {
    gdpShare: 25,
    currentProgress: 12.5,
    industrialExports: 500,
    currentExports: 285
  }
};


const INDUSTRIES_DATA = [
  {
    id: "petrochemicals",
    name: "البتروكيماويات",
    icon: "fa-industry",
    color: "#2C3E50",
    description: "تُعدّ صناعة البتروكيماويات العمود الفقري للاقتصاد الصناعي السعودي، وتضم المملكة أكبر مجمعات البتروكيماويات في العالم.",
    cities: ["jubail", "yanbu", "jizan"],
    gdpShare: 35,
    exports: "180 مليار ريال",
    companies: 85,
    image: "jubail_industrial_city.png"
  },
  {
    id: "food",
    name: "الصناعات الغذائية",
    icon: "fa-wheat-awn",
    color: "#D4AF37",
    description: "تشهد الصناعات الغذائية نمواً متسارعاً في المملكة، مدفوعةً بالطلب المحلي المتزايد ومستهدفات الأمن الغذائي في رؤية 2030.",
    cities: ["riyadh", "jeddah", "hail", "madinah"],
    gdpShare: 18,
    exports: "45 مليار ريال",
    companies: 1200,
    image: "jeddah_industrial_city.png"
  },
  {
    id: "steel",
    name: "الحديد والصلب",
    icon: "fa-hammer",
    color: "#34495E",
    description: "تمتلك المملكة طاقة إنتاجية ضخمة في صناعة الحديد والصلب، تدعم مشاريع البنية التحتية الكبرى وقطاع الإنشاءات.",
    cities: ["jubail", "jizan"],
    gdpShare: 12,
    exports: "38 مليار ريال",
    companies: 45,
    image: "jubail_integrated_petrochemical_complex.png"
  },
  {
    id: "pharmaceuticals",
    name: "الصناعات الدوائية",
    icon: "fa-pills",
    color: "#C9A961",
    description: "تسعى المملكة إلى تحقيق الاكتفاء الذاتي في الصناعات الدوائية، وتوطين 40% من الاحتياجات الدوائية بحلول 2030.",
    cities: ["riyadh", "sudair"],
    gdpShare: 8,
    exports: "12 مليار ريال",
    companies: 180,
    image: "sudair_generic_pharma_factory.png"
  },
  {
    id: "construction",
    name: "مواد البناء",
    icon: "fa-building",
    color: "#666666",
    description: "تدعم صناعة مواد البناء مشاريع التطوير العمراني الضخمة في المملكة، بما فيها مشاريع رؤية 2030 الكبرى كنيوم والقدية.",
    cities: ["riyadh", "dammam", "hail", "taif"],
    gdpShare: 10,
    exports: "22 مليار ريال",
    companies: 650,
    image: "saudi_construction_materials.png"
  },
  {
    id: "logistics",
    name: "اللوجستيات والتوزيع",
    icon: "fa-truck",
    color: "#2C3E50",
    description: "تسعى المملكة لتحويل نفسها إلى مركز لوجستي عالمي يربط ثلاث قارات، مستفيدةً من موقعها الجغرافي الاستراتيجي.",
    cities: ["jeddah", "dammam", "jubail"],
    gdpShare: 7,
    exports: "15 مليار ريال",
    companies: 320,
    image: "dammam_integrated_logistics_hub.png"
  }
];


const VISION_2030_DATA = {
  targets: [
    { id: 1, title: "رفع مساهمة الصناعة في الناتج المحلي", current: 12.5, target: 25, unit: "%" },
    { id: 2, title: "زيادة الصادرات غير النفطية", current: 285, target: 500, unit: "مليار ريال" },
    { id: 3, title: "توطين الوظائف الصناعية", current: 42, target: 60, unit: "%" },
    { id: 4, title: "استقطاب الاستثمار الأجنبي", current: 145, target: 300, unit: "مليار ريال" },
    { id: 5, title: "تطوير المدن الصناعية", current: 36, target: 50, unit: "مدينة" }
  ],
  pillars: [
    { title: "التنويع الاقتصادي", description: "تقليل الاعتماد على النفط وتطوير قطاعات صناعية متنوعة" },
    { title: "توطين الصناعة", description: "دعم الشركات المحلية وتطوير سلاسل الإمداد الوطنية" },
    { title: "الاستثمار الأجنبي", description: "استقطاب الشركات العالمية وتوفير بيئة استثمارية محفزة" },
    { title: "التحول الرقمي", description: "تبني تقنيات الثورة الصناعية الرابعة في المصانع السعودية" }
  ]
};


const INVESTMENT_OPPORTUNITIES = [
  {
    id: "tech-manufacturing",
    title: "التصنيع التقني المتقدم",
    sector: "التقنية",
    minInvestment: "50 مليون ريال",
    expectedReturn: "15-20%",
    timeframe: "5-7 سنوات",
    description: "فرص استثمارية في تصنيع المعدات التقنية والإلكترونيات والمكونات الذكية",
    incentives: ["إعفاء ضريبي 10 سنوات", "أراضٍ بأسعار مدعومة", "دعم في التدريب"],
    city: "riyadh",
    image: "saudi_smart_manufacturing.png"
  },
  {
    id: "renewable-energy",
    title: "صناعات الطاقة المتجددة",
    sector: "الطاقة",
    minInvestment: "200 مليون ريال",
    expectedReturn: "12-18%",
    timeframe: "8-10 سنوات",
    description: "تصنيع ألواح الطاقة الشمسية وتوربينات الرياح ومعدات الطاقة المتجددة",
    incentives: ["دعم من صندوق الاستثمارات العامة", "عقود حكومية مضمونة", "إعفاءات جمركية"],
    city: "jubail",
    image: "saudi_petrochemicals_refinery.png"
  },
  {
    id: "food-security",
    title: "صناعات الأمن الغذائي",
    sector: "الغذاء",
    minInvestment: "30 مليون ريال",
    expectedReturn: "18-25%",
    timeframe: "3-5 سنوات",
    description: "مصانع تجهيز الغذاء والمنتجات الزراعية لتحقيق الأمن الغذائي الوطني",
    incentives: ["دعم وزارة البيئة والمياه", "قروض ميسرة", "أولوية في العقود الحكومية"],
    city: "hail",
    image: "jeddah_industrial.png"
  },
  {
    id: "pharma",
    title: "الصناعات الدوائية والطبية",
    sector: "الصحة",
    minInvestment: "100 مليون ريال",
    expectedReturn: "20-28%",
    timeframe: "6-8 سنوات",
    description: "تصنيع الأدوية والمستلزمات الطبية لتحقيق الاكتفاء الذاتي الصحي",
    incentives: ["دعم هيئة الغذاء والدواء", "إعفاء ضريبي كامل", "تسهيل التسجيل والترخيص"],
    city: "sudair",
    image: "madinah_industrial.png"
  }
];


const TIMELINE_DATA = [
  { year: 1975, event: "تأسيس هيئة المدن الصناعية ومناطق التقنية (مدن)", description: "بداية التخطيط الاستراتيجي للتطوير الصناعي في المملكة", milestone: true },
  { year: 1975, event: "إطلاق مشروع مدينة الجبيل الصناعية", description: "أحد أضخم مشاريع التطوير الصناعي في تاريخ البشرية" },
  { year: 1975, event: "إطلاق مشروع مدينة ينبع الصناعية", description: "تطوير المنطقة الغربية كمركز صناعي بتروكيماوي" },
  { year: 1977, event: "تأسيس المدينة الصناعية في جدة", description: "تطوير أكبر مدينة صناعية في المنطقة الغربية" },
  { year: 1985, event: "توسعة المدن الصناعية وإضافة مدن جديدة", description: "مرحلة التوسع الثانية للمدن الصناعية السعودية", milestone: true },
  { year: 2000, event: "إطلاق برنامج التطوير الصناعي الشامل", description: "تحديث البنية التحتية وتطوير الخدمات الصناعية" },
  { year: 2005, event: "إنشاء مدن صناعية في المناطق النائية", description: "توسيع التطوير الصناعي ليشمل جميع مناطق المملكة" },
  { year: 2016, event: "إطلاق رؤية المملكة 2030", description: "تحول استراتيجي نحو التنويع الاقتصادي والتصنيع المتقدم", milestone: true },
  { year: 2017, event: "إطلاق برنامج تطوير الصناعة الوطنية والخدمات اللوجستية", description: "تعزيز التصنيع المحلي وتطوير سلاسل الإمداد" },
  { year: 2020, event: "إطلاق الاستراتيجية الصناعية الوطنية", description: "خطة شاملة لتطوير القطاع الصناعي حتى 2035" },
  { year: 2022, event: "مضاعفة الاستثمارات في المدن الصناعية", description: "ضخ استثمارات ضخمة لتطوير البنية التحتية الصناعية", milestone: true },
  { year: 2030, event: "مستهدفات رؤية 2030 الصناعية", description: "رفع مساهمة الصناعة في الناتج المحلي إلى 25%", milestone: true }
];


if (typeof module !== 'undefined') {
  module.exports = { CITIES_DATA, ECONOMIC_STATS, INDUSTRIES_DATA, VISION_2030_DATA, INVESTMENT_OPPORTUNITIES, TIMELINE_DATA };
}
